----------------------
Exploração de Dados
----------------------

```{r}
#setwd('~/Área de trabalho/Backup/ENGENHARIA/FORMACAO DATA SCIENCE - Udemy/MATERIAIS/9.Pratica em R')

require("knitr")
#opts_knit$set(root.dir = '~/Área de trabalho/Backup/ENGENHARIA/FORMACAO DATA SCIENCE - Udemy/MATERIAIS/9.Pratica em R')
getwd()

#importa dados, string vazio como NA, string como fatores

dados = read.csv("~/Área de trabalho/Backup/ENGENHARIA/FORMACAO DATA SCIENCE - Udemy/MATERIAIS/9.Pratica em R/dados/Churn.csv",sep = ";",header = TRUE, na.strings = "",stringsAsFactors = TRUE) 

```


```{r}
getwd()
head(dados)
summary(dados)
```

Colunas


```{r}
#Dar nomes corretos as colunas

colnames(dados) = c("Id","Score","Estado","Genero","Idade","Patrimonio","Saldo","Produtos","TemCartCredito","Ativo","Salario","Saiu")

head(dados)
```

#Explorar Dados, Colunas Categóricas

```{r}

#Estados
counts = table(dados$Estado)

counts

barplot(counts, main ="Estados", xlab = "Estados")

#Genero

counts2 = table(dados$Genero)

barplot(counts2, main = "Gênero", xlab = "Gênero")
```

Exploração de Colunas Numéricas


```{r}
#Score

summary(dados$Score)
boxplot(dados$Score)

hist(dados$Score)
```


Idade 

```{r}

summary(dados$Idade)

boxplot(dados$Idade)
hist(dados$Idade)

```

Saldo 

```{r}

summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```

Salário

```{r}

summary(dados$Salario)
boxplot(dados$Salario)
hist(dados$Salario)

```

